# Kevin Zhang
# kevin.zhang.13499@gmail.com
# 104939334
default:
		gcc -Wall -Wextra -o lab1a lab1a.c
clean: 
		rm -f *.o lab1a *.tar.gz
dist: default
		tar -czf lab1a-104939334.tar.gz lab1a.c Makefile README
