#NAME: Kevin Zhang, Jack Li
#EMAIL: kevin.zhang.13499@gmail.com, jackli2014@gmail.com
#ID: 104939334, 604754714

default:
	gcc -Wall -Wextra -lm -o lab3a lab3a.c
dist: default
	tar -czvf lab3a-104939334.tar.gz Makefile README lab3a.c ext2_fs.h
clean:
	rm lab3a *.tar.gz
